# Site settings
title: Adam Fendley
description: Software Development Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: http://gravitylow.github.io

# User settings
username: Adam Fendley
user_title: Software Developer
email: adam.fendley@gmail.com
twitter_username: gravity_low
github_username:  gravitylow
linkedin_username:  adam-fendley-6b31456a

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
